name: Game Idea Testing
description: Test a Game Idea
labels: [testing]
body:
  - type: textarea
    attributes:
      label: Challenge Idea
      description: |
        Reference the accepted PR of the game idea that you want to test.
    validations:
      required: true
