name: Game Idea Proposal
description: Propose a Game Idea
labels: [idea]
body:
  - type: textarea
    attributes:
      label: Challenge Idea
      description: |
        Descript your challenge idea in detail. You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Required Capabilities
      description: |
        List down the required capabilities the player need to overcome this challenge.
        Reference the PR that implements the capabilities that is already implemented.
        Elaborate on new capabilities.
    validations:
      required: true
