name: Game Idea Integration
description: Integrate a Game Idea
labels: [integration]
body:
  - type: textarea
    attributes:
      label: Level Design
      description: |
        Explain how the level is presented to the player.
        Reference the accepted PRs of the game testing that you want to include in your level.
    validations:
      required: true
